### PR TITLE
TypeError: group.add is not a function

### LINKED ISSUE #7: TypeError: group.add is not a function
This error is thrown in the `selectionHelpers.syncGroupSelection` method.

### PR DESCRIPTION
**Pull request by astefanutti**
Fixes #7

### CODE REVIEW

**Comment by gashcrumb** [comment]
Same as #6, need the updated `dist/hawtio-utilities.js`, then I can merge these and do a release for ya.

**Comment by astefanutti** [comment]
Rebased and repushed. Thanks!

**Comment by gashcrumb** [comment]
Awesome, thanks!  Lemme get a release out with these fixes...

**Comment by astefanutti** [comment]
👍!

**Comment by gashcrumb** [comment]
@astefanutti done, `bower update` should get you an updated `hawtio-utilities` and `hawtio-ui`...

**Comment by astefanutti** [comment]
That was too fast 😉! Thanks!

**Pull request merged**
